version: '2'
services:

  # This is the database to which the all the other components in the stack will connect and interact with
  # Having the database in a container is very convenient in development but in production you will
  # use a separate database instance, like Amazon RDS, i.e. in production this section will be
  # commented and in the .env file you will specify the ip of your separate database instance
  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    ports:
      - "5432:5432"
    environment:
      # the values are defined in the .env file
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${SUPER_USER}
      - POSTGRES_PASSWORD=${SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # env vars useful for our sql scripts
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DEVELOPMENT=${DEVELOPMENT}
      - JWT_SECRET=${JWT_SECRET}

    volumes:
      - "./db/src:/docker-entrypoint-initdb.d"

  subzero:
    container_name: subzero
    # this is a development image limited to 1 database connection in the pool
    # for production use the image below (you'll need a 'On Premise' subscription)
    # image: registry.subzero.cloud/subzero
    image: subzerocloud/subzero-development 
    ports:
      - "8080:80"
      - "4443:443"
    environment:
      # the values are defined in the .env file
      # postgrest
      - PGRST_DB_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?application_name=subzero
      - PGRST_JWT_SECRET=${JWT_SECRET}
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      - PGRST_SERVER_PROXY_URI=${SERVER_PROXY_URI}
      # uncomment to see also postgrest output in the logs
      # - PGRST_LOGFILE=/dev/fd/1
      # - PGRST_LOG_LEVEL=info
      
      # openresty
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DEVELOPMENT=${DEVELOPMENT}
      - ENABLE_CACHE=${ENABLE_CACHE}
      - ERR_LOGLEVEL=info

      # oauth providers
      - OAUTH_SUCCESS_URI=/rest/rpc/on_oauth_login
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID}
      - OAUTH_FACEBOOK_CLIENT_SECRET=${OAUTH_FACEBOOK_CLIENT_SECRET}

    # volumes:
    #   - ./openresty/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    #   - ./openresty/nginx/oauth.conf:/usr/local/openresty/nginx/conf/oauth.conf
